sudo: required
services:
  - docker

before_install:
  - docker build -t ahmetensar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ahmetensar/react-test npm run test -- --coverage

after_success:
  - docker build -t ahmetensar/multi-client ./client
  - docker build -t ahmetensar/multi-nginx ./nginx
  - docker build -t ahmetensar/multi-server ./server
  - docker build -t ahmetensar/multi-worker ./worker
  
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push ahmetensar/multi-client
  - docker push ahmetensar/multi-nginx
  - docker push ahmetensar/multi-server
  - docker push ahmetensar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-020118764398
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY